dependencies:
  - aave/protocol-v2@1.0.1
  - aave/aave-v3-core@1.16.2
  - uniswap/v2-core@1.0.1
  - uniswap/v3-core@1.0.0
  
  - aave/protocol-v2@1.0.1
  - aave/aave-v3-core@1.16.2
  - uniswap/v2-core@1.0.0
  - uniswap/v2-periphery@1.0.0-beta.0
  - uniswap/v3-core@1.0.0
  - uniswap/v3-periphery@1.3.0

compiler:
  solc:
    remappings:
      - '@aave2=aave/protocol-v2@1.0.1'
      - '@aave3=aave/aave-v3-core@1.16.2'
      - '@uniswap2=uniswap/v2-core@1.0.0'
      - '@uniswap3=uniswap/v3-core@1.0.0'
    remappings:
      - '@aave_v2=aave/protocol-v2@1.0.1'
      - '@aave_V3=aave/aave-v3-core@1.16.2'
      - '@uniswap_core_v2=uniswap/v2-core@1.0.0'
      - '@uniswap_periphery_v2=uniswap/v2-periphery@1.0.0-beta.0'
      - '@uniswap_core_v3=uniswap/v3-core@1.0.0'
      - '@uniswap_periphery_v3=uniswap/v3-periphery@1.3.0'
      
dotenv: .env

networks:
  default: mainnet

  mainnet:

    aave_pool_addresses_provider: '0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5'
    ether_pricefeed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    protocol_data_provider: '0x057835Ad21a177dbdd3090bB1CAE03EaCF78Fc6d'
    uniswapV2Factory: '0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f'
    uniswapV3Factory: '0x1F98431c8aD98523631AE4a59f267346ea31F984'

  goerli:
    link_token: '0x326C977E6efc84E512bB9C30f76E30c160eD06FB'
    lendingPoolAddressProvider: '0x5E52dEc931FFb32f609681B8438A51c675cc232d'
    poolAdressesProvider: '0xc4dCB5126a3AfEd129BC3668Ea19285A9f56D15D'
    uniswapV2Factory: '0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f'
    uniswapV3Factory: '0x1F98431c8aD98523631AE4a59f267346ea31F984'

  polygon-main:
    aave_pool_addresses_provider: '0xa97684ead0e402dC232d5A977953DF7ECBaB3CDb'
    ether_pricefeed: '0xF9680D99D6C9589e2a93a78A04A279e509205945'
    protocol_data_provider: '0x7551b5D2763519d4e37e8B81929D336De671d46d'
    uniswapV3Factory: '0x1F98431c8aD98523631AE4a59f267346ea31F984'





wallets:
  from_key: ${PRIVATE_KEY_DADAIA}